# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweetsdata',
            old_name='kcal',
            new_name='kcal_100',
        ),
        migrations.RenameField(
            model_name='sweetsdata',
            old_name='weight_grams',
            new_name='serving_grams',
        ),
        migrations.AddField(
            model_name='sweetsdata',
            name='carbohydrate_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweetsdata',
            name='fat_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweetsdata',
            name='protein_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
