# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_auto_20180515_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweetsdata',
            name='serving_grams',
        ),
        migrations.AlterField(
            model_name='sweetsdata',
            name='carbohydrate_100',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sweetsdata',
            name='fat_100',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sweetsdata',
            name='kcal_100',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sweetsdata',
            name='protein_100',
            field=models.FloatField(),
        ),
    ]
