# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_auto_20180812_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetsdata',
            name='sugar_100',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
