# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carplate',
            name='plate_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
