# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_fact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact',
            field=models.CharField(max_length=400),
        ),
    ]
